# Use root/example as user/password credentials for mongodb
# Use admin/pass as user/password credentials for mongo-express http login
version: '3.1'

services:

  mongo:
    container_name: mongo-tom-1
    image: mongo
    restart: always
    ports:
      - 38018:27017
    env_file:
      - .env-mongo

  mongo-express:
    container_name: mongo-express-tom-1
    image: mongo-express
    restart: always
    ports:
      - 8089:8081
    env_file:
      - .env-mongo-express
